package main

import (
	"slices"
	"strconv"
	"strings"

	"github.com/gin-gonic/gin"
)

// Struct that represents a node in the evaluation tree generated by the parser.
// Each node contains a value (operator or number) and pointers to its left and right children.
type Tree struct {
	value string
	left  *Tree
	right *Tree
}

func main() {
	router := gin.Default()
	router.POST("/calculate", calculate)
	router.Run("localhost:8080")
}

// Handler function for the /calculate endpoint.
// It processes the input expression, tokenizes it (lexer), parses it into an evaluation tree (parser), and evaluates the result (evaluator).
func calculate(c *gin.Context) {
	// Call lexer
	tokens, error := lexer(c.Query("form"))
	if error != "" {
		c.JSON(400, gin.H{
			"error": error,
		})
		return
	}

	// Call parser
	evalTree, error := parser(tokens)
	if error != "" {
		c.JSON(400, gin.H{
			"error": error,
		})
		return
	}

	// Call evaluator
	result, error := evaluator(*evalTree)
	if error != "" {
		c.JSON(400, gin.H{
			"error": error,
		})
		return
	}

	// Response if everything went fine
	c.JSON(200, gin.H{
		"result": result,
	})
}

// Lexer function that takes a mathematical expression as input and returns a slice of tokens and an error message if any invalid tokens are found.
func lexer(form string) ([]string, string) {
	var tokens []string
	var error string = ""

	// remove all white space
	form = strings.Replace(form, " ", "", -1)
	// split form into tokens
	tokens = strings.Split(form, "")

	// check if all tokens are valid
	for i := 0; i < len(tokens); i++ {
		if !((tokens[i] >= "0" && tokens[i] <= "9") || slices.Contains([]string{"+", "-", "*", "/", "(", ")"}, tokens[i])) {
			error = "Invalid token: " + tokens[i]
			break
		}
	}
	return tokens, error
}

// Parser function that takes a slice of tokens and constructs an evaluation tree using a recursive descent parsing approach.
// It returns the root of the evaluation tree and an error message if any issues are encountered during parsing.
func parser(tokens []string) (*Tree, string) {
	var evalTree Tree
	var parensCount int = 0
	var error string = ""

	// Add a missing * operator between a number and a parenthesis
	for i := 0; i < len(tokens); i++ {
		if tokens[i] == "(" && i > 0 {
			if tokens[i-1] >= "0" && tokens[i-1] <= "9" {
				tokens = slices.Insert(tokens, i, "*")
			}
		}
		if tokens[i] == ")" && i < len(tokens)-1 {
			if tokens[i+1] >= "0" && tokens[i+1] <= "9" {
				tokens = slices.Insert(tokens, i+1, "*")
			}
		}
	}

	// Process addition and subtraction
	for i := 0; i < len(tokens); i++ {
		if tokens[i] == "(" {
			parensCount++
		}
		if tokens[i] == ")" {
			parensCount--
		}

		if parensCount == 0 {
			if tokens[i] == "+" || tokens[i] == "-" {
				if !(tokens[i+1] >= "0" && tokens[i+1] <= "9") {
					error = "Multiple operators in a row"
					return nil, error
				}
				evalTree.value = tokens[i]
				evalTree.left, error = parser(tokens[0:i])
				evalTree.right, error = parser(tokens[i+1:])
				return &evalTree, error
			}
		}
	}

	// Check for mismatched parentheses
	if parensCount != 0 {
		error = "Mismatched parentheses"
		return nil, error
	}

	// Process multiplication and division
	for i := 0; i < len(tokens); i++ {
		if tokens[i] == "(" {
			parensCount++
		}
		if tokens[i] == ")" {
			parensCount--
		}

		if parensCount == 0 {
			if tokens[i] == "*" || tokens[i] == "/" {
				if tokens[i+1] == "+" || tokens[i+1] == "-" {
					error = "Multiple operators in a row"
					return nil, error
				}
				evalTree.value = tokens[i]
				evalTree.left, error = parser(tokens[0:i])
				evalTree.right, error = parser(tokens[i+1:])
				return &evalTree, error
			}
		}
	}

	// Check for mismatched parentheses
	if parensCount != 0 {
		error = "Mismatched parentheses"
		return nil, error
	}

	// Check for parentheses
	if tokens[0] == "(" && tokens[len(tokens)-1] == ")" {
		if len(tokens) < 3 {
			error = "Empty parentheses"
			return nil, error
		}
		// Remove the outer parentheses and parse the inner expression
		return parser(tokens[1 : len(tokens)-1])
	}

	if (tokens[0] >= "0" && tokens[0] <= "9") && (tokens[len(tokens)-1] >= "0" && tokens[len(tokens)-1] <= "9") {
		// If the expression is a single number, return it as a leaf node
		evalTree.value = strings.Join(tokens, "")
		return &evalTree, error
	}

	return nil, error
}

// Evaluator function that takes the root of an evaluation tree and recursively computes the result of the mathematical expression represented by the tree.
func evaluator(evalTree Tree) (int, string) {
	var error string = ""

	if (evalTree.value == "+" || evalTree.value == "-" || evalTree.value == "*" || evalTree.value == "/") && evalTree.left != nil && evalTree.right != nil {
		_, leftErr := strconv.Atoi(evalTree.left.value)
		_, rightErr := strconv.Atoi(evalTree.right.value)
		if leftErr != nil {
			leftResult, _ := evaluator(*evalTree.left)
			evalTree.left.value = strconv.Itoa(leftResult)
			leftErr = nil
		}
		if rightErr != nil {
			rightResult, _ := evaluator(*evalTree.right)
			evalTree.right.value = strconv.Itoa(rightResult)
			rightErr = nil
		}
		if leftErr == nil && rightErr == nil {
			leftVal, _ := strconv.Atoi(evalTree.left.value)
			rightVal, _ := strconv.Atoi(evalTree.right.value)
			switch evalTree.value {
			case "+":
				return leftVal + rightVal, error
			case "-":
				return leftVal - rightVal, error
			case "*":
				return leftVal * rightVal, error
			case "/":
				if rightVal == 0 {
					error = "Division by zero"
					return -1, error
				}
				return leftVal / rightVal, error
			}
		}
	}
	return -1, error
}
