package main

import (
	"github.com/gin-gonic/gin"
)

// Struct that represents a node in the evaluation tree generated by the parser.
// Each node contains a value (operator or number) and pointers to its left and right children.
type Tree struct {
	value string
	left  *Tree
	right *Tree
}

func main() {
	router := gin.Default()
	router.POST("/calculate", calculate)
	router.Run("localhost:8080")
}

// Handler function for the /calculate endpoint.
// It processes the input expression, tokenizes it (lexer), parses it into an evaluation tree (parser), and evaluates the result (evaluator).
func calculate(c *gin.Context) {
	// Call lexer
	tokens, error := lexer(c.Query("form"))
	if checkForErrors(error, c) {
		return
	}

	// Call parser
	evalTree, error := parser(tokens)
	if checkForErrors(error, c) {
		return
	}

	// Call evaluator
	result, error := evaluator(*evalTree)
	if checkForErrors(error, c) {
		return
	}

	// Response if everything went fine
	c.JSON(200, gin.H{
		"result": result,
	})
}

// Helper function to check for errors and set the JSON response if an error is found.
func checkForErrors(error string, c *gin.Context) bool {
	if error != "" {
		c.JSON(400, gin.H{
			"error": error,
		})
		return true
	}
	return false
}
